version: '3.9'

services:
  enshrouded:
    image: 'enshrouded:0.1'
    ports:
      - "tbd:tbd"
      - "tbd:tbd"
    volumes:
      - "serverdata:/Enshrouded"
    networks:
      - "backendnetwork"
    Environment:
      - "TBD=tdb"

volumes:
  serverdata:

networks:
  backendnetwork:
    attachable: true
