version: '3.9'

services:
  enshrouded:
    image: 'chevalierpinard/enshrouded:0.1'
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "15636:15636/udp"
      - "15637:15667/udp"
      - "tbd:tbd"
    volumes:
      - "serverdata:/home/steam/enshrouded"
    networks:
      - "backendnetwork"
    Environment:
      - "ENSHROUDED_SERVER_NAME=myenshroudedserver"
      - "ENSHROUDED_SERVER_PASSWORD=<insertpasswordhere>"
      - "ENSHROUDED_SERVER_SAVEDIRECTORY=./savegame"
      - "ENSHROUDED_SERVER_LOGDIRECTORY=./logs"
      - "ENSHROUDED_SERVER_MAXPLAYERS=16"

volumes:
  serverdata:

networks:
  backendnetwork:
    attachable: true
